version: '3.8'
services:

    # Application
    app:
        build:
            context: .
            dockerfile: ./docker/app.dockerfile
        container_name: elastic-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
    # Web Server
    web:
        build:
            context: .
            dockerfile: ./docker/web.dockerfile
        container_name: elastic-nginx
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - "8012:80"